### ISSUE TITLE
Find an interesting dataset and make it model ready

### ISSUE THREAD

**Issue by zepam** [UW-MLGEO/MLGEO2024_Geldingadalir#9]

**Comment by kasialp8** [comment]
Some ideas for datasets to use 

[ground motion from Kilauea volcano system, Hawaii](https://www.strongmotioncenter.org/specialstudies/moschetti2018_hawaii/) 

[seismic data on the site originally used by authors](https://geofon.gfz-potsdam.de/waveform/archive/more) includes Nazca plate subduction zone

[PNSN stations](https://www.pnsn.org/seismograms ) -> for Washington and Oregon, good for PNW data 

[volcano data](https://www.pnsn.org/seismograms?region=volcanoes ) specifically in PNW

**Comment by kasialp8** [comment]
Dataset prepared
